### PR TITLE
Fix HMR, update to Router 4, Update Routes, add Oscillator

### LINKED ISSUE #7: build home page

### LINKED ISSUE #10: React Router

### LINKED ISSUE #34: Header / Navigation Bar
Need to incorporate a nav bar into every view so the user can access other pages, login / create account, sign out, visit new sound view, visit new composition view, view profile of saved info, etc.

### PR DESCRIPTION
**Pull request by esayler**
Fixes HMR in most cases (may get an error about reducer not hot-reloading), and: 

- Resolves #34  adds Header with navbar. 
- Resolves #10 by updates to Router 4, and configuring routes
- Resolves #7 by adding Route to Home page
- Starts #4: adds the start of the Oscillator to `SoundMaker` that is still based on local stat

- Adds thunk and router-redux middleware for redux

Planning on updating the Oscillator (`SoundMaker`) to possibly rely more on redux. Another TODO is to clean up some of the Oscillator code.

### CODE REVIEW

File: lib/components/App/index.jsx [hunk 1]
```diff
@@ -0,0 +1,25 @@
+import React, { Component } from 'react'
+import { Route, Switch } from 'react-router-dom'
+import UserProfile from '../UserProfile'
+import Sequencer from '../Sequencer'
+import SoundMaker from '../SoundMaker'
+import Header from '../Header'
+import Home from '../Home'
+
```
Comment (dylanavery720) [inline lib/components/App/index.jsx]: does this need to be a .jsx file? .js might cause less probs

File: lib/components/App/index.jsx [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+export class App extends Component {
+  render() {
+    return (
+      <div>
+        <Header />
+        <Switch>
```
Comment (dylanavery720) [inline lib/components/App/index.jsx]: Does this replace Provider?

File: lib/components/Header/index.jsx [hunk 3]
```diff
@@ -0,0 +1,19 @@
+import React from 'react'
+import './header-style'
+import { Link } from 'react-router-dom'
+
+const Header = () => {
+  return (
+    <div className="Header">
+      <Link to='/'><h1>FutureGrooves</h1></Link>
+      <nav>
+        <Link to='/'>Home</Link>
```
Comment (dylanavery720) [inline lib/components/Header/index.jsx]: nice!

File: lib/components/SoundMaker/index.jsx [hunk 4]
```diff
@@ -0,0 +1,296 @@
...
+     const newHold = Math.fround(e.target.value)
+     this.setState(update(this.state, { spec: { env: { hold: { $set: newHold } } } }))
+  }
+
+  updateRelease(e) {
+     const newRelease = Math.fround(e.target.value)
+     this.setState(update(this.state, { spec: { env: { release: { $set: newRelease } } } }))
+  }
+
+  updateFilterType(e) {
```
Comment (dylanavery720) [inline lib/components/SoundMaker/index.jsx]: we should be able to make these all dynamic one function eventually (hopefully)
